
import "swiper/css"
import 'tailwindcss/tailwind.css';
import '../../../public/assets/css/tailwind-built.css'
import '../../../public/assets/css/animate.min.css'

//trasnaltions
import initTranslations from '../../i18n';
import TranslationsProvider from '../../../components/TranslationsProvider';

import { Poppins, Montserrat } from 'next/font/google'

const poppins = Poppins({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: "--poppins",
	display: 'swap',
})

const montserrat = Montserrat({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: "--montserrat",
	display: 'swap',
})


export const metadata = {
	title: 'NextJS Tailwind CSS landing page',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }) {
	const locale = params?.locale;
	if (!locale) return null;
	const { resources } = await initTranslations(locale, [
		'home',
		"about",
		"header",
		"servicesPage",
		"contact",
		"signup",
		"login",
		"user",
		"footer",
		"publicServices",
		"publicMarket"
	]);
	return (
		<html lang="en">
			<body className={`${poppins.variable} ${montserrat.variable}`}>
				<TranslationsProvider
					locale={locale}
					namespaces={['home']}
					resources={resources}
				>

					{children}
				</TranslationsProvider>
			</body>
		</html>
	)
}
